Description of Timers
Timers
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
start Inits the state machine
start Set the controlled motor obj.ctrledMotor in PWM control mode.
Timers
This function is called by:
RateThread
Timers
unitTests Add main folders in Matlab path
SUBFUNCTIONS
function aTimer = staticTimer(varargin)
function wait(delay)
SOURCE CODE
classdef Timers < handle
    %Handler of timers
    %   This class provides services related to timers handling:
    %   - it can create a timer for handling blocking delays
    %     (the used timer is a static attribute)
    properties(Constant = true, GetAccess = public)
        waitTimer = Timers.staticTimer();
    end
    methods(Static = true)
        % Create static timer for delay handling
        function aTimer = staticTimer(varargin)
            aTimer = timer('ExecutionMode','singleShot','TimerFcn',@(~,~){});
        end
        % Wait for a delay in seconds (blocking)
        function wait(delay)
            set(Timers.waitTimer,'StartDelay',delay);
            start(Timers.waitTimer);
            wait(Timers.waitTimer);
        end
    end
end