Description of waitPortOpen
waitPortOpen
PURPOSE
Waits for specified port to open.
SYNOPSIS
function [ ok ] = waitPortOpen(port,timeout)
DESCRIPTION
Waits for specified port to open.
   Every 100 ms, we check specified port is open.
CROSS-REFERENCE INFORMATION
This function calls:
start Inits the state machine
start Set the controlled motor obj.ctrledMotor in PWM control mode.
stop Stop the PWM controller.
This function is called by:
SensorDataYarpI
SUBFUNCTIONS
function checkPortIsOpen(obj,port)
SOURCE CODE
function [ ok ] = waitPortOpen(port,timeout)
%Waits for specified port to open.
%   Every 100 ms, we check specified port is open.
% define polling function (timer callback)
timerFcn = @(timerObj,~) checkPortIsOpen(timerObj,port);
% create timeout timer
poller = timer(...
    'ExecutionMode','fixedRate',...
    'Period',0.1,...
    'TasksToExecute',timeout/0.1,...
    'TimerFcn',timerFcn,...
    'UserData',false);
% start timer and wait
start(poller);
wait(poller);
% return motion done success or failure
ok = get(poller,'UserData');
end
% polling function
function checkPortIsOpen(obj,port)
% check if port is open
if yarp.Network.exists(port)
    % port is open. Set the completion flag to true
    set(obj,'UserData',true);
    % stop the timer
    stop(obj);
end
end