Description of S
S
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
S
This function is called by:
S
ellipse_im2ex Cast ellipse defined with implicit parameter vector to explicit form.
ellipse_im2kepler Cast ellipse defined with standard parameter vector to Kepler form.
ellipsefit_direct Direct least squares fitting of ellipses.
ellipsoid_ex2im Cast ellipsoid defined with explicit parameters to implicit vector form.
ellipsoid_im2ex Cast ellipsoid defined with implicit parameter vector to explicit form.
ellipsoidfit Fit an ellipsoid to data by minimizing point-to-surface distance.
ellipsoidfit_direct Direct least squares fitting of ellipsoids under the constraint 4J - I^2 > 0.
ellipsoidfit_simple Simple iterative least squares fitting of ellipsoids under the constraint k*J - I^2 > 0.
ellipsoidsym Symbolic expression of ellipsoid in implicit form with center, axes and quaternions.
example_kcrlb Demonstration of fitting algoritm performance compared to KCR-LB.
quad2d_similarity Translate data to place centroid at origin and apply isotropic scaling.
quad2dfit_cals Fit a quadratic curve to data using consistent algebraic least squares.
quad2dfit_leastsquares Fit a quadratic curve to a set of 2D data points using least-squares.
symm Create a matrix of symbolic variables.
symmd Create a diagonal matrix of symbolic variables.
symms Create a symmetric matrix of symbolic variables.
sgolay SGOLAY Savitzky-Golay Filter Design.
SOURCE CODE
classdef S < uint8
    %This class defines the possible states of the 'LowlevTauCtrlCalibrator' state machine.
    %   Detailed explanation goes here
    enumeration
        stateStart       (1)
        stateAcqFriction (2)
        stateFitFriction (3)
        stateAcqKtau     (4)
        stateFitKtau     (5)
        stateNextGroup   (6)
        stateEnd         (7)
    end
end