Description of y
y
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
y
This function is called by:
getPlotDataNfitModel
plotterThreadUpdateFcn UNTITLED Summary of this function goes here
Plotter
plotFuncTimeseries UNTITLED9 Summary of this function goes here
plotFuncTimeseriesNderivative UNTITLED9 Summary of this function goes here
Regressors
frictionModel1Sym frictionModel1Sym Computes the closed-form solution to linear regression
frictionModel2 frictionModel2 Computes the closed-form solution to linear regression
normalEquationAsym NORMALEQUATION Computes the closed-form solution to linear regression
pwmModel1Sym pwmModel1Sym Computes the closed-form solution to linear regression
residuals UNTITLED Summary of this function goes here
SensorDiagnosis
ellipsoid_proj_distance_fromExp Projections and distance of points projected onto an ellipsoid.
loadData LOADDATA Summary of this function goes here
y
unitTests Add main folders in Matlab path
circlefit Fit a circle to data using the least squares approach.
ellipse Generates points along an ellipse.
ellipse_distance Distance of points projected onto an ellipse.
ellipse_orbital Generates points along an ellipse using Kepler's parameters.
ellipsefit Fit an ellipse to data by minimizing point-to-curve distance.
ellipsefit_direct Direct least squares fitting of ellipses.
ellipsefit_foot Maximum likelihood ellipse fit with foot points.
ellipsefit_koopmans Fit an ellipse to data using the nonlinear Koopmans method.
ellipsoid_distance Distance of points projected onto an ellipsoid.
ellipsoid_ex2im Cast ellipsoid defined with explicit parameters to implicit vector form.
ellipsoid_projections Plots ellipsoid projections on the xy, xz and yz planes.
ellipsoidfit Fit an ellipsoid to data by minimizing point-to-surface distance.
ellipsoidfit_aml Approximated maximum likelihood fit of ellipsoids.
ellipsoidfit_direct Direct least squares fitting of ellipsoids under the constraint 4J - I^2 > 0.
ellipsoidfit_koopmans Fit an ellipsoid to data using the nonlinear Koopmans method.
ellipsoidfit_leastsquares Fit an ellipsoid to a set of 3D data points.
ellipsoidfit_residuals Finds the distance of the point (x,y,z) to the nearest point on the ellipsoid.
ellipsoidfit_simple Simple iterative least squares fitting of ellipsoids under the constraint k*J - I^2 > 0.
ellipsoidsym Symbolic expression of ellipsoid in implicit form with center, axes and quaternions.
example_ellipsefit1 Demonstration of various ellipse (and general quadratic curve) fits.
example_ellipsefit2 Various ellipse fits to some data points.
example_ellipsefitsector Ellipse fitting to data from a limited sector.
example_ellipsenormfit Comparing the accuracy of various ellipse fits with and without normals.
example_ellipseproj Demonstration of projecting points to an ellipse.
example_ellipsoid A sample ellipsoid.
example_ellipsoidcomp Comparative demonstration of fits to random ellipsoids.
example_ellipsoidfit1 Demonstration of various ellipsoid fits.
example_ellipsoidfit2 Demonstration of fits to various special ellipsoids.
example_kcrlb Demonstration of fitting algoritm performance compared to KCR-LB.
example_parabolafit Demonstration of parabola fitting.
example_planefit Demonstration of plane fitting.
example_quad2dcomp Comparison of various ellipse (and general quadratic curve) fits.
example_quad2dcon Demonstration of constrained quadratic curve fitting.
example_spherefit Demonstration of least-squares sphere fit.
imconic Compute parameters of or plot conic section given in implicit form.
imconicisect Intersections of conic with window bounds.
imconictranslate Translates a conic section given as an implicit equation.
lineclip Draw a line with clipping using the Cohen-Sutherland algorithm.
nntrifaces Nearest-neighbor triangle face vertex indices.
parabolafit_cals Fit a parabola using consistent algebraic least squares.
parabolafit_direct Direct least squares fitting of parabolas.
planefit Plane fit to noisy 3D data points.
plot_ellipsoid Plot ellipsoid specified with center, radii and rotation matrix.
plot_ellipsoid_im Plot ellipsoid specified with implicit parameters.
plot_ellipsoid_part Plot ellipsoid specified with center, radii and rotation matrix.
plot_sphere_part Partial sphere surface.
plotconvhull Plot convex hull of a set of data points.
pqdist Distance of point(s) and quadratic curve or quadric surface.
quad2d_similarity Translate data to place centroid at origin and apply isotropic scaling.
quad2dconfit_koopmans Fit a constrained quadratic curve to data using the nonlinear Koopmans method.
quad2dcov Theoretical noise covariance structure corresponding to a 2D quadratic function.
quad2dcovred Reduced-size noise covariance structure corresponding to a 2D quadratic function.
quad2dfit_cals Fit a quadratic curve to data using consistent algebraic least squares.
quad2dfit_hyperaccurate General quadratic curve fit with Kanatani's hyperaccurate fit method.
quad2dfit_koopmans Fit a quadratic curve to data using the nonlinear Koopmans method.
quad2dfit_leastsquares Fit a quadratic curve to a set of 2D data points using least-squares.
quad2dfit_lsnormal Fit a quadratic curve to a set of 2D data points with normals.
quad2dfit_paramchk Quadratic 2-D fitting parameter check.
quad2dfit_taubin General quadratic curve fit with Taubin's method.
quad3d_center Center of a central quadric (quadratic surface).
quad3dcovmat Theoretical noise covariance matrix corresponding to a 3D quadratic function.
quad3dcovpoly Theoretical noise covariance structure corresponding to a 3D quadratic function.
quad3dfit_koopmans Fit a quadratic curve to data using the nonlinear Koopmans method.
quad3dfit_paramchk Quadratic 2-D fitting parameter check.
quad3dfit_taubin General quadric surface fit with Taubin's method.
quadmake Builds covariance matrices for quadratic forms.
quat2rot Convert quaternion to rotation matrix.
rot3d Rotate points in three dimensions.
sphere_gd Construct a geodesic sphere.
spherefit Fit a sphere to data using the least squares approach.
test_sympoly Test suite for symbolic polynomial manipulation.
sgolayfilt SGOLAYFILT Savitzky-Golay Filtering.
sgolayFiltParamsTuning % clear all variables and close all previous figures
SUBFUNCTIONS
function vocabInt = vocabEnc(vocabString)
function vocabString = vocabDec(vocabInt)
SOURCE CODE
classdef y
    %Y Class implementing a few YARP constants not handled by the bindings
    %   Detailed explanation goes here
    properties(Constant) %, Access=protected)
        aVocab = yarp.Vocab();
    end
    properties(Constant)
        VOCAB_CM_IDLE            = y.vocabEnc('idl');
        VOCAB_CM_TORQUE          = y.vocabEnc('torq');
        VOCAB_CM_POSITION        = y.vocabEnc('pos');
        VOCAB_CM_POSITION_DIRECT = y.vocabEnc('posd');
        VOCAB_CM_VELOCITY        = y.vocabEnc('vel');
        VOCAB_CM_CURRENT         = y.vocabEnc('icur');
        VOCAB_CM_PWM             = y.vocabEnc('ipwm');
        VOCAB_PIDTYPE_POSITION   = y.vocabEnc('pos');
        VOCAB_PIDTYPE_VELOCITY   = y.vocabEnc('vel');
        VOCAB_PIDTYPE_TORQUE     = y.vocabEnc('trq');
        VOCAB_PIDTYPE_CURRENT    = y.vocabEnc('cur');
    end
    methods(Static = true)
        function vocabInt = vocabEnc(vocabString)
            % we cast the vocab integer to double otherwise the fromMatlab
            % conversion fails (copies 0s instead of the actual values.
            % This should be due to a memory misalignment).
            vocabInt = double(y.aVocab.encode(vocabString));
        end
        function vocabString = vocabDec(vocabInt)
            vocabString = y.aVocab.decode(vocabInt);
        end
    end
end