% Maps the a link (left_leg,right_arm) to the part the link belongs to.

arm_links = @(side) {...
    [side '_shoulder_1'],[side '_shoulder_2'],[side '_shoulder_3'],...
    [side '_upper_arm'],[side '_elbow_1'],[side '_forearm'],...
    [side '_wrist_1'],[side '_hand']};
leg_links = @(side) {...
    [side '_hip_1'],[side '_hip_2'],[side '_hip_3'],...
    [side '_upper_leg'],[side '_lower_leg'],...
    [side '_ankle_1'],[side '_ankle_2'],[side '_foot']};

left_arm_links = arm_links('l');
right_arm_links = arm_links('r');
left_leg_links = leg_links('l');
right_leg_links = leg_links('r');
torso_links = {'root_link','torso_1','torso_2','chest'};
head_links = {'neck_1','neck_2','head'};

mappingInHeader = {'link' 'part'};

mappingInLA = left_arm_links'; mappingInLA(:,2) = {'left_arm'};
mappingInRA = right_arm_links'; mappingInRA(:,2) = {'right_arm'};
mappingInLL = left_leg_links'; mappingInLL(:,2) = {'left_leg'};
mappingInRL = right_leg_links'; mappingInRL(:,2) = {'right_leg'};
mappingInTO = torso_links'; mappingInTO(:,2) = {'torso'};
mappingInHD = head_links'; mappingInHD(:,2) = {'head'};

mappingIn = [...
    mappingInHeader;...
    mappingInLA;...
    mappingInRA;...
    mappingInLL;...
    mappingInRL;...
    mappingInTO;...
    mappingInHD];
