Description of stop
stop
PURPOSE
Stop the PWM controller.
SYNOPSIS
function [ ok ] = stop(obj)
DESCRIPTION
Stop the PWM controller.
   This also restores the previous control mode for the named motor and
   eventual coupled motors.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
MotorPWMcontroller
RateThread
waitMotionDone Waits for last programmed joint position to be reached.
waitPortOpen Waits for specified port to open.
example_ellipsefit1 Demonstration of various ellipse (and general quadratic curve) fits.
SOURCE CODE
function [ ok ] = stop(obj)
%Stop the PWM controller.
%   This also restores the previous control mode for the named motor and
%   eventual coupled motors.
if obj.running
    % stop the emulator thread if it's running. As the thread stops, it
    % should trigger the restoration of the previous control mode
    obj.ctrllerThread.stop(true);
    ok = true;
else
    % The current PWM control mode didn't require an emulator thread. Just
    % restore the previous control mode
    ok = obj.remCtrlBoardRemap.setJointsControlMode(obj.couplingMotorIdxes,obj.couplingPrevMode);
end
% Controller back to default init state
% stop and delete plotter thread
obj.plotterThread.stop(true);
delete(obj.plotterThread);
if ~isempty(obj.ctrllerThread)
    delete(obj.ctrllerThread);
end
obj.controllerReady = false;
end