Description of savePlot
savePlot
PURPOSE
UNTITLED6 Summary of this function goes here
SYNOPSIS
function savePlot(figuresHandler,savePlot,exportPlot,dataPath)
DESCRIPTION
UNTITLED6 Summary of this function goes here
   Detailed explanation goes here
CROSS-REFERENCE INFORMATION
This function calls:
savePlot UNTITLED6 Summary of this function goes here
This function is called by:
LowlevTauCtrlCalibrator
plotTrainingData This function plots the acquired data for the friction or ktau calibration
savePlot UNTITLED6 Summary of this function goes here
runDiagnosis Parameters specific to this diagnosis function:
sensorSelfCalibratorInit ====================================================================
SOURCE CODE
function savePlot(figuresHandler,savePlot,exportPlot,dataPath)
%UNTITLED6 Summary of this function goes here
%   Detailed explanation goes here
% Save the plots into matlab figure files and eventually export them to PNG
% files.
if savePlot
    % save plots
    [figsFolder,iterator] = figuresHandler.saveFigures(exportPlot);
    % create log info file
    fileID = fopen([figsFolder '.txt'],'w');
    fprintf(fileID,'figs folder = %s\n',[dataPath '/' figsFolder]);
    fprintf(fileID,'iterator = %d\n',iterator);
    %fprintf(fileID,whos);
    fclose(fileID);
end
end