Description of FilterContext
FilterContext
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
FilterContext
tuneFilter UNTITLED3 Summary of this function goes here
This function is called by:
FilterContext
sgolayFiltParamsTuning % clear all variables and close all previous figures
SUBFUNCTIONS
function obj = FilterContext(K,F,time,sensMeas,contextPath)
function regSubPlots(obj,ax,ay,az)
SOURCE CODE
classdef FilterContext < handle
    %UNTITLED Summary of this class goes here
    %   Detailed explanation goes here
    properties
        SgolayK;
        SgolayF;
        time;
        sensMeas;
        lastFilteredSensMeas = [];
        deltaF;
        adjustedDeltaF; % always even
        ax;
        ay;
        az;
        contextPath = '';
    end
    methods
        function obj = FilterContext(K,F,time,sensMeas,contextPath)
            obj.SgolayK = K;
            obj.SgolayF = F;
            obj.time = time;
            obj.sensMeas = sensMeas;
            obj.lastFilteredSensMeas = sensMeas;
            obj.deltaF = 1;
            obj.adjustedDeltaF = 2;
            obj.contextPath = contextPath;
        end
        function regSubPlots(obj,ax,ay,az)
            obj.ax = ax;
            obj.ay = ay;
            obj.az = az;
        end
    end
    methods(Static)
        tuneFilter(hObject,callbackdata,filterContext)
    end
end