Description of GridGeneratorWOsuspend
GridGeneratorWOsuspend
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
GridGenerator
getMeasTagsFromPaths For each pair of simultaneous target positions , set the tag
GridGeneratorWOsuspend
getMeasTagsFromPaths For each pair of simultaneous target positions , set the tag
This function is called by:
GridGeneratorWOsuspend
accelerometersCalibratorSequenceProfileWOsuspend % Home single step sequence
gyroscopesCalibratorSequenceProfile1checkAlgo % Home single step sequence
gyroscopesCalibratorSequenceProfile2checkCalib % Home single step sequence
SUBFUNCTIONS
function obj = GridGeneratorWOsuspend()
SOURCE CODE
classdef GridGeneratorWOsuspend < GridGenerator
    %GridGeneratorWOpause This class generates the same grid as
    %   GridGenerator, but the acquisition is never suspended during
    %   transition motions.
    methods(Access = public)
        function obj = GridGeneratorWOsuspend()
        end
    end
    methods(Access = protected)
        measTag = getMeasTagsFromPaths(obj,qT);
    end
end