classdef Plotter < handle
    %UNTITLED8 Summary of this class goes here
    %   Detailed explanation goes here
    
    properties(Constant)
        colorPanel = {'b','g','r','c','m','y'};
    end
    
    methods (Static=true)
        plot2funcTimeseries(...
            figuresHandler,aTitle,aLabel,...
            time,y1,y2,...
            yLabel,y1Legend,y2Legend);
        
        plotFuncTimeseriesNderivative(...
            figuresHandler,aTitle,aLabel,...
            time,y,dtFrac,dy,...
            yLabel,yLegend,dydtLegend);
        
        plot2funcTimeseriesYY(...
            figuresHandler,aTitle,aLabel,...
            time1,y1,time2,y2,...
            yLabel1,yLabel2);
        
        plot2dDataNfittedModel(...
            figuresHandler,aTitle,aLabel,...
            xData,yData,xModel,yModel,...
            xLabel,yLabel,...
            dataLegend,modelLegend);
    end
    
end

