classdef Plotter < handle
    %UNTITLED8 Summary of this class goes here
    %   Detailed explanation goes here
    
    properties(Constant)
        rad2deg = @(x) x*180/pi;
        colorPanel = {'b','g','r','c','m','y'};
        % the figures handles and properties
        figuresHandlerMap = containers.Map('KeyType','char','ValueType','any');
    end
    
    methods (Static=true)
        plotFuncTimeseries(...
            figuresHandler,aTitle,aLabel,...
            time,y,...
            yLabel);
        
        plot2funcTimeseries(...
            figuresHandler,aTitle,aLabel,...
            time,y1,y2,...
            yLabel,y1Legend,y2Legend);
        
        figH = plotNFuncTimeseries(...
            figuresHandler,aTitle,aLabel,yLabel,...     % params irrelevant if figH is not empty
            time,Y,yLegends,...                               % params always required
            lineStyles,lineWidth,markerCycle,figH,resetPlot,alphas); % params always required
        
        plotFuncTimeseriesNderivative(...
            figuresHandler,aTitle,aLabel,...
            time,y,dtFrac,dy,...
            yLabel,yLegend,dydtLegend);
        
        plot2funcTimeseriesYY(...
            figuresHandler,aTitle,aLabel,...
            time1,y1,time2,y2,...
            yLabel1,yLabel2,y1Legend,y2Legend);
        
        plot2dDataNfittedModel(...
            figuresHandler,aTitle,aLabel,...
            xData,yData,xModel,yModel,...
            xLabel,yLabel,...
            dataLegend,modelLegend);
        
        [ figH,animLinesList ] = plotNanimLineTimeseries(...
            figuresHandler,aTitle,aLabel,yLabel,...
            yLegends,lineStyles,lineWidths,colors,...
            markerSymbols,markerSizes,markerEdgeColors,markerFaceColors);
    end
    
end

