Description of nDimGrid
nDimGrid
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
nDimGrid
This function is called by:
calibrateSensors Get calibration map
nDimGrid
SUBFUNCTIONS
function obj = nDimGrid(dimension,range,resolution)
function vector = getVector(obj,idx)
SOURCE CODE
classdef nDimGrid < handle
    % this class builds a N-dimension grid for specified dimension, range and
    % resolution. It alows to retrieve a vector from that grid through a
    % linear index.
    properties (SetAccess = public, GetAccess = public)
        grid;
        dimension = 0;
        nbVectors = 0;
    end
    methods
        function obj = nDimGrid(dimension,range,resolution)
            % define grid
            obj.grid = cell(1,dimension);
            obj.dimension = dimension;
            % build output string
            outputString = 'obj.grid{1}';
            for iter = 2:obj.dimension
                outputString = [outputString ',obj.grid{' num2str(iter) '}'];
            end
            %disp(outputString);
            % fill the grid
            eval(['[' outputString '] = ndgrid(' num2str(-range) ':' ...
                                                 num2str(resolution) ':' ...
                                                 num2str(range) ');'])
            % set the total number of vectors that can be generated
            obj.nbVectors = numel(obj.grid{1});
        end
        function vector = getVector(obj,idx)
            vectorT = zeros(length(idx),obj.dimension);
            for iter = 1:obj.dimension
                vectorT(:,iter) = obj.grid{iter}(idx);
            end
            vector = vectorT';
        end
    end
end