Description of LowlevTauCtrlCalibrator_SM
LowlevTauCtrlCalibrator_SM
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
LowlevTauCtrlCalibrator_SM
LowlevTauCtrlCalibrator
This function is called by:
LowlevTauCtrlCalibrator_SM
SUBFUNCTIONS
function obj = LowlevTauCtrlCalibrator_SM()
function acquire(obj,frictionOrKtau)
function fit(obj,frictionOrKtau)
function discardAcqFriction(obj)
function discardAcqKtau(obj)
function plotTrainingData(obj,path,sensors,parts,model,taskSpec)
function calibrateSensors(~,
function theInstance = instance()
SOURCE CODE
classdef LowlevTauCtrlCalibrator_SM < LowlevTauCtrlCalibrator
    %For unit testing the class 'LowlevTauCtrlCalibrator' state transitions.
    %   Detailed explanation goes here
    properties(Constant=true, Access=protected)
        UT_singletonObj = UT.LowlevTauCtrlCalibrator_SM();
    end
    methods(Access=protected)
        function obj = LowlevTauCtrlCalibrator_SM()
            obj.savePlotCallback = @() disp('savePlot');
            % Debug mode
            obj.isDebugMode = true;
        end
        % state machine methods
        function acquire(obj,frictionOrKtau)
            disp(['acquire(' frictionOrKtau ')']);
            disp(obj.state);
            motorName = obj.expddMotorList{obj.state.currentMotorIdx};
            disp(['motor name: ' motorName]);
            part = obj.model.jointsDbase.getPartFromMotors(motorName);
            disp(['part :' part]);
        end
        function fit(obj,frictionOrKtau)
            disp(['fit(' frictionOrKtau ')']);
            disp(obj.state);
            motorName = obj.expddMotorList{obj.state.currentMotorIdx};
            disp(['motor name: ' motorName]);
            part = obj.model.jointsDbase.getPartFromMotors(motorName);
            disp(['part :' part]);
        end
        function discardAcqFriction(obj)
            disp(['discardAcqFriction']);
            disp(obj.state);
        end
        function discardAcqKtau(obj)
            disp(['discardAcqKtau']);
            disp(obj.state);
        end
        function plotTrainingData(obj,path,sensors,parts,model,taskSpec)
            disp('plotTrainingData() with parameters:');
            celldisp({obj,path,sensors,parts,model,taskSpec});
        end
        function calibrateSensors(~,...
            dataPath,~,measedSensorList,measedPartsList,...
            model,taskSpecificParams)
            disp('calibrateSensors() with parameters:');
            celldisp({dataPath,measedSensorList,measedPartsList,model,taskSpecificParams});
        end
    end
    methods(Static=true, Access=public)
        % this function should initialize properly the shared attribute
        % 'singletonObj' and returns the handle to the caller
        function theInstance = instance()
            theInstance = UT.LowlevTauCtrlCalibrator_SM.UT_singletonObj;
        end
    end
end