Description of SensorDataAcquisition
SensorDataAcquisition
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
SensorDataAcquisition
acquireSensorData task: this selects the motion sequence parameters
getSeqProfile getSeqProfile Loads the sequence profile parameters from a script ini file
setValFromGrid parse the grid parameters (creates vars 'part1','joint1','part2'...)
This function is called by:
SensorDataAcquisition
SOURCE CODE
classdef SensorDataAcquisition
    %UNTITLED2 Summary of this class goes here
    %   Detailed explanation goes here
    properties(Constant=true, Access=public)
        task@char = 'sensorDataAcquisition';
        initSection@char = 'sensorsTestDataAcq';
    end
    methods(Static = true, Access = public)
        acqSensorDataAccessor = ...
            acquireSensorData(task,taskSpecificParams,robotModel,dataPath,calibedParts);
        seqParams = setValFromGrid(gridBuilder,gridParams,acqVel,transVel,labels);
    end
    methods(Static = true, Access = protected)
        [seqHomeParams,seqEndParams,selector] = getSeqProfile(task,taskSpecificParams);
    end
end