
%% Home single step sequence

% In this context, 'robotModel' is defined as an object of class RobotModel.
% For limbs calibration
homeCalibLimbs.labels = {...
    'ctrl','ctrl','ctrl','ctrl','ctrl','ctrl';...
    'pos','pos','pos','pos','pos','pos';
    'left_arm','right_arm','left_leg','right_leg','torso','head'};
homeCalibLimbs.val = {...
    [0 45 0 0 0 0 0],...
    [0 45 0 0 0 0 0],...
    [0 10 0 0 0 0],...
    [0 10 0 0 0 0],...
    [0 0 0],...
    [0 0 0]};

% For torso calibration
homeCalibTorso = homeCalibLimbs;
homeCalibTorso.val = {...
    [-30 30 -30 80 0 0 0],...
    [-30 30 -30 80 0 0 0],...
    [0 10 0 0 0 0],...
    [0 10 0 0 0 0],...
    [0 0 0],...
    [0 0 0]};

%% Motion sequences
% (a single sequence is intended to move all defined parts synchronously,
% motions from 2 different sequences should be run asynchronously)
% each calibPart should be caibrated within a single sequence.

% define grid motion patterns for each limb

%% common parameters
gridBuilder = GridGeneratorWOsuspend();
acqVel = 4; transVel = 4;

%% Left and right arms
left_arm_seqParams.labels = {...
    'ctrl'               ,'ctrl'          ,'meas'     ,'meas'     ,'meas'     ;...
    'pos'                ,'vel'           ,'joint'    ,'joint'    ,'acc'      ;...
    'left_arm'           ,'left_arm'      ,'left_arm' ,'torso'    ,'left_arm'};

gridParams = {...
    'joint'          ,'qmin','qmax','nbInterv';...
    'l_shoulder_roll', 20   , 116   , 6       ;...
    'l_shoulder_yaw' ,-23   ,  49   , 6       };

left_arm_seqParams.val = SensorDataAcquisition.setValFromGrid(...
    gridBuilder,gridParams,acqVel,transVel,left_arm_seqParams.labels,robotModel);

right_arm_seqParams.labels = {...
    'ctrl'               ,'ctrl'          ,'meas'     ,'meas'     ,'meas'      ;...
    'pos'                ,'vel'           ,'joint'    ,'joint'    ,'acc'       ;...
    'right_arm'          ,'right_arm'     ,'right_arm','torso'    ,'right_arm'};

right_arm_seqParams.val = left_arm_seqParams.val;

%% Left and right legs
left_leg_seqParams.labels = {...
    'ctrl'               ,'ctrl'          ,'meas'     ,'meas'    ;...
    'pos'                ,'vel'           ,'joint'    ,'acc'     ;...
    'left_leg'           ,'left_leg'      ,'left_leg' ,'left_leg'};

gridParams = {...
    'joint'     ,'qmin','qmax','nbInterv';...
    'l_hip_roll', 20   , 80   , 6        ;...
    'l_hip_yaw' ,-60   , 60   , 6        };

left_leg_seqParams.val = SensorDataAcquisition.setValFromGrid(...
    gridBuilder,gridParams,acqVel,transVel,left_leg_seqParams.labels,robotModel);

right_leg_seqParams.labels = {...
    'ctrl'               ,'ctrl'          ,'meas'     ,'meas'     ;...
    'pos'                ,'vel'           ,'joint'    ,'acc'      ;...
    'right_leg'          ,'right_leg'     ,'right_leg','right_leg'};

right_leg_seqParams.val = left_leg_seqParams.val;

%% Torso
torso_seqParams.labels = {...
    'ctrl'       ,'ctrl'          ,'meas'     ,'meas' ;...
    'pos'        ,'vel'           ,'joint'    ,'acc'  ;...
    'torso'      ,'torso'         ,'torso'    ,'torso'};

gridParams = {...
    'joint'      ,'qmin','qmax','nbInterv';...
    'torso_pitch',-14   , 60   , 6        ;...
    'torso_yaw'  ,-48   , 48   , 6        };

torso_seqParams.val = SensorDataAcquisition.setValFromGrid(...
    gridBuilder,gridParams,acqVel,transVel,torso_seqParams.labels,robotModel);

%% Head
head_seqParams.labels = {...
    'ctrl'       ,'ctrl'          ,'meas'     ,'meas'     ,'meas';...
    'pos'        ,'vel'           ,'joint'    ,'joint'    ,'imu' ;...
    'head'       ,'head'          ,'head'     ,'torso'    ,'head'};

gridParams = {...
    'joint'     ,'qmin','qmax','nbInterv';...
    'neck_pitch',-25   , 15   , 6        ;...
    'neck_yaw'  ,-45   , 45   , 6        };

head_seqParams.val = SensorDataAcquisition.setValFromGrid(...
    gridBuilder,gridParams,acqVel,transVel,head_seqParams.labels,robotModel);

%% define sequences for limbs {1} and torso {2} calibration
seqHomeParams{1} = homeCalibLimbs;
seqHomeParams{2} = homeCalibTorso;
seqEndParams     = homeCalibLimbs;

%% Map parts to sequences and params
selector.calibedParts = {...
    'left_arm','right_arm',...
    'left_leg','right_leg',...
    'torso','head'};
selector.calibedSensors = {...
    {'acc'},{'acc'},...
    {'acc'},{'acc'},...
    {'acc'},{'acc'}};
selector.setIdx  = {1,1,1,1,2,1}; % max index must not exceed max index of seqHomePArams
selector.seqParams = {...
    left_arm_seqParams,right_arm_seqParams,...
    left_leg_seqParams,right_leg_seqParams,...
    torso_seqParams,head_seqParams};

