Description of ellipsefit_koopmans
ellipsefit_koopmans
PURPOSE
Fit an ellipse to data using the nonlinear Koopmans method.
SYNOPSIS
function [theta,mu] = ellipsefit_koopmans(varargin)
DESCRIPTION
 Fit an ellipse to data using the nonlinear Koopmans method.
 Input arguments:
 x, y:
    vectors of data to fit
 sigma_x, sigma_y:
    noise parameter for x and y dimensions
CROSS-REFERENCE INFORMATION
This function calls:
y
quad2dconfit_koopmans Fit a constrained quadratic curve to data using the nonlinear Koopmans method.
quad2dfit_paramchk Quadratic 2-D fitting parameter check.
This function is called by:
example_ellipsefit1 Demonstration of various ellipse (and general quadratic curve) fits.
example_ellipsefitsector Ellipse fitting to data from a limited sector.
example_kcrlb Demonstration of fitting algoritm performance compared to KCR-LB.
example_quad2dcomp Comparison of various ellipse (and general quadratic curve) fits.
SOURCE CODE
function [theta,mu] = ellipsefit_koopmans(varargin)
% Fit an ellipse to data using the nonlinear Koopmans method.
%
% Input arguments:
% x, y:
%    vectors of data to fit
% sigma_x, sigma_y:
%    noise parameter for x and y dimensions
% Copyright 2012 Levente Hunyadi
[x,y,sigma_x,sigma_y] = quad2dfit_paramchk(mfilename, varargin{:});
[theta,~,mu] = quad2dconfit_koopmans(x, y, sigma_x, sigma_y, 'ellipse');