Description of ellipsoid_distance
ellipsoid_distance
PURPOSE
Distance of points projected onto an ellipsoid.
SYNOPSIS
function d = ellipsoid_distance(x,y,z,p)
DESCRIPTION
 Distance of points projected onto an ellipsoid.
 Input arguments:
 x, y, z:
    co-ordinates of data points whose distance from the ellipsoid to measure
 p:
    parameters of the ellipsoid expressed in implicit form
CROSS-REFERENCE INFORMATION
This function calls:
y
ellipsoid_im2ex Cast ellipsoid defined with implicit parameter vector to explicit form.
ellipsoidfit_residuals Finds the distance of the point (x,y,z) to the nearest point on the ellipsoid.
This function is called by:
SOURCE CODE
function d = ellipsoid_distance(x,y,z,p)
% Distance of points projected onto an ellipsoid.
%
% Input arguments:
% x, y, z:
%    co-ordinates of data points whose distance from the ellipsoid to measure
% p:
%    parameters of the ellipsoid expressed in implicit form
% Copyright 2011 Levente Hunyadi
[center,radii,~,R] = ellipsoid_im2ex(p);
[xp,yp,zp] = ellipsoidfit_residuals(x,y,z, center,radii,R);
d = (x-xp).^2 + (y-yp).^2 + (z-zp).^2;