Description of example_pqdist
example_pqdist
PURPOSE
Sample code for distance of quadratic curve and point.
SYNOPSIS
function example_pqdist
DESCRIPTION
 Sample code for distance of quadratic curve and point.
 See also: pqdist
CROSS-REFERENCE INFORMATION
This function calls:
imconic Compute parameters of or plot conic section given in implicit form.
imconicrotate Rotates a conic section given as an implicit equation.
pqdist Distance of point(s) and quadratic curve or quadric surface.
This function is called by:
SOURCE CODE
function example_pqdist
% Sample code for distance of quadratic curve and point.
%
% See also: pqdist
% Copyright 2010 Levente Hunyadi
% ellipse
p = imconicrotate([9 0 16 90 -64 145], pi/6);
P = transpose([0,1 ; -3,-6 ; -7,-3 ; -7,0]);  % each P = (Px,Py)
[dst,F] = pqdist(P, p); %#ok<ASGLU>
figure('Name', 'Distance of points from ellipse');
hold('all');
imconic(p);
for k = 1 : size(F,2)
    plot([P(1,k) F(1,k)],[P(2,k) F(2,k)],'r');
end
axis equal
hold('off');
% hyperbola
p = imconicrotate([1 0 -1 0 0 -1], 7*pi/8);
P = transpose([0,1 ; -3,-6 ; -7,-3 ; -7,0 ; 10,5 ; 10,-10 ; 0,15]);  % each P = (Px,Py)
[dst,F] = pqdist(P, p); %#ok<ASGLU>
figure('Name', 'Distance of points from hyperbola');
hold('all');
imconic(p);
for k = 1 : size(F,2)
    plot([P(1,k) F(1,k)],[P(2,k) F(2,k)],'r');
end
axis equal
hold('off');