Description of imconicdiscr
imconicdiscr
PURPOSE
Discriminant for conic section.
SYNOPSIS
function D = imconicdiscr(p)
DESCRIPTION
 Discriminant for conic section.
 See also: imconic
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
imconic Compute parameters of or plot conic section given in implicit form.
imconicrotation Rotation matrix of a conic section given as an implicit equation.
imconictranslation Translation vector of a conic section given as an implicit equation.
SOURCE CODE
function D = imconicdiscr(p)
% Discriminant for conic section.
%
% See also: imconic
% Copyright 2010 Levente Hunyadi
a = p(1);
b = 0.5*p(2);
c = p(3);
D = det([ a b ; b c ]);