Description of Regressors
Regressors
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
Regressors
frictionModel1Sym frictionModel1Sym Computes the closed-form solution to linear regression
frictionModel2 frictionModel2 Computes the closed-form solution to linear regression
normalEquationAsym NORMALEQUATION Computes the closed-form solution to linear regression
pwmModel1Sym pwmModel1Sym Computes the closed-form solution to linear regression
resampleDataAsym UNTITLED Summary of this function goes here
resampleDataModel UNTITLED Summary of this function goes here
resampleDataSym UNTITLED Summary of this function goes here
residuals UNTITLED Summary of this function goes here
y
This function is called by:
Regressors
SOURCE CODE
classdef Regressors < handle
    %UNTITLED8 Summary of this class goes here
    %   Detailed explanation goes here
    properties
    end
    methods (Static=true)
        [thetaPos,thetaNeg] = normalEquationAsym(x,y);
        model = pwmModel1Sym(x,y);
        model = frictionModel1Sym(x,y);
        model = frictionModel2(x,y);
        [xs,ys] = resampleDataAsym(thetaPos,thetaNeg,x,nSamples);
        [xs,ys] = resampleDataSym(theta,x,nSamples);
        [xs,ys] = resampleDataModel(model,x,nSamples);
        resVec = residuals(thetaPos,thetaNeg,x,y);
    end
end